import json
import os
import traceback
from datetime import datetime

from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import StreamingResponse
from sqlalchemy import func
from sqlalchemy.orm import Session

from app.agent import get_current_agent
from app.config import INPUT_TOKEN_PRICE_PER_1K, OUTPUT_TOKEN_PRICE_PER_1K
from app.database import ConversationLog
from app.evaluator import HallucinationCallback
from app.schemas import AgentStep, ChatRequest, ChatResponse, TokenUsage, UsageStats

router = APIRouter(prefix="", tags=["chat"])


def logging_turns(
    db: Session,
    user_id: int,
    thread_id: str,
    thread_name: str,
    role: str,
    content: str,
):
    max_turn = (
        db.query(func.max(ConversationLog.turn_number))
        .filter(
            ConversationLog.user_id == user_id,
            ConversationLog.thread_id == thread_id,
        )
        .scalar()
    )
    next_turn = (max_turn or -1) + 1

    log = ConversationLog(
        user_id=user_id,
        thread_id=thread_id,
        thread_name=thread_name,
        turn_number=next_turn,
        role=role,
        content=content,
    )
    db.add(log)
    db.commit()


LOG_DIR = os.path.join(
    os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))),
    "logs",
)
os.makedirs(LOG_DIR, exist_ok=True)


def _write_trace_from_parts(
    thread_id: str,
    user_message: str,
    trace_lines: list[str],
    response_text: str | None = None,
    error: str | None = None,
    usage: dict | None = None,
):
    ts = datetime.now().strftime("%Y-%m-%d_%H%M%S")
    filename = f"thread_{thread_id}_{ts}.md"
    filepath = os.path.join(LOG_DIR, filename)

    with open(filepath, "w", encoding="utf-8") as f:
        f.write("# Agent Trace\n\n")
        f.write("**Thread:** `" + thread_id + "`  \n")
        now_str = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        f.write("**Date:** " + now_str + "\n\n---\n\n")
        f.write("## User\n\n" + user_message + "\n\n")
        f.write("".join(trace_lines))
        if error:
            f.write("### Error\n\n```\n" + error + "\n```\n\n")
        if response_text:
            f.write("## Response\n\n" + response_text + "\n\n")
        if usage:
            token_line = "---\n\n**Tokens:** " + str(usage["total_tokens"]) + "  \n"
            cost_line = "**Cost:** $" + "{:.6f}".format(usage["cost_usd"]) + "\n\n"
            f.write(token_line + cost_line + "*Generated by Vetlog AI Agent*\n")
        else:
            f.write(
                "\n---\n\n*Trace truncated -- stream terminated before completion.*\n"
            )


def _write_trace_log(
    thread_id: str, user_message: str, messages: list, usage: dict | None = None
):
    """
    Write a human-readable Markdown trace of the agent's execution
    to logs/ for debugging.
    """
    ts = datetime.now().strftime("%Y-%m-%d_%H%M%S")
    filename = f"thread_{thread_id}_{ts}.md"
    filepath = os.path.join(LOG_DIR, filename)

    with open(filepath, "w", encoding="utf-8") as f:
        f.write("# Agent Trace\n\n")
        f.write("**Thread:** `" + thread_id + "`  \n")
        now_str = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        f.write("**Date:** " + now_str + "\n\n---\n\n")

        for msg in messages:
            class_name = type(msg).__name__

            if class_name == "HumanMessage":
                f.write("## User\n\n" + str(msg.content) + "\n\n")

            elif class_name == "ToolMessage":
                content = getattr(msg, "content", "") or ""
                f.write("### Tool Result\n\n")
                if content.startswith("Error"):
                    f.write(str(content) + "\n\n")
                elif content.startswith("reports/") and "Rows:" in content:
                    for line in content.strip().splitlines()[:3]:
                        f.write(str(line) + "  \n")
                    f.write("\n")
                elif content.startswith("reports/"):
                    f.write("Saved: `" + str(content) + "`\n\n")
                elif content == "No results found.":
                    f.write("0 rows returned\n\n")
                else:
                    lines = []
                    for l in content.strip().splitlines():
                        if l.strip():
                            lines.append(l)
                    rows = max(0, len(lines) - 1)
                    row_label = "row"
                    if rows != 1:
                        row_label = "rows"
                    f.write(str(rows) + " " + row_label + " returned\n\n")
                    if lines:
                        f.write(str(lines[0][:200]) + "\n\n")

            elif class_name == "AIMessage":
                content = getattr(msg, "content", "") or ""
                tool_calls = getattr(msg, "tool_calls", []) or []

                for tc in tool_calls:
                    name = tc.get("name", "")
                    args = tc.get("args", {})
                    f.write("### " + name + "\n\n")
                    if "query" in name.lower():
                        query = args.get("query", "")
                        f.write("```sql\n" + query + "\n```\n\n")
                    elif "report" in name.lower():
                        f.write("title: " + str(args.get("title", "")) + "\n\n")
                    else:
                        f.write("args: " + json.dumps(args)[:200] + "\n\n")

                if content:
                    f.write("## Response\n\n" + str(content) + "\n\n")

        if usage:
            f.write("---\n\n")
            f.write("**Tokens:** " + str(usage.get("total_tokens", 0)) + "  \n")
            cost_str = "{:.6f}".format(usage.get("cost_usd", 0))
            f.write("**Cost:** $" + cost_str + "\n")
        f.write("\n*Generated by Vetlog AI Agent*\n")

    return filename


def _sse(payload: dict) -> str:
    """Format a dict as a Server-Sent-Events `data:` line."""
    return f"data: {json.dumps(payload)}\n\n"


def _tool_output_str(raw_output) -> str:
    """Normalise a tool's raw output into a plain string."""
    if hasattr(raw_output, "content"):
        output = raw_output.content or ""
        if isinstance(output, list):
            parts = []
            for b in output:
                if isinstance(b, dict):
                    parts.append(b.get("text", ""))
                else:
                    parts.append(str(b))
            output = " ".join(parts)
        return output
    if isinstance(raw_output, str):
        return raw_output
    return str(raw_output)


def _iter_chunk_texts(content) -> list[str]:
    """Extract plain text pieces from a streaming chunk's content."""
    texts: list[str] = []
    if isinstance(content, str):
        if content:
            texts.append(content)
    elif isinstance(content, list):
        for block in content:
            if isinstance(block, dict) and block.get("type") == "text":
                t = block.get("text", "")
                if t:
                    texts.append(t)
    return texts


# In-memory usage accumulator
_usage = {
    "total_requests": 0,
    "total_input_tokens": 0,
    "total_output_tokens": 0,
    "total_tokens": 0,
    "total_cost_usd": 0.0,
}


def extract_content(message) -> str:
    content = message.content
    if isinstance(content, str):
        return content
    parts = []
    for block in content:
        if isinstance(block, str):
            parts.append(block)
        else:
            parts.append(block.get("text", ""))
    return " ".join(parts)


def extract_usage(messages: list) -> TokenUsage:
    total_input = 0
    total_output = 0
    for message in messages:
        metadata = getattr(message, "usage_metadata", None)
        if metadata is None:
            continue
        total_input += metadata.get("input_tokens", 0)
        total_output += metadata.get("output_tokens", 0)

    input_cost = (total_input / 1000) * INPUT_TOKEN_PRICE_PER_1K
    output_cost = (total_output / 1000) * OUTPUT_TOKEN_PRICE_PER_1K
    total_cost = round(input_cost + output_cost, 6)

    return TokenUsage(
        input_tokens=total_input,
        output_tokens=total_output,
        total_tokens=total_input + total_output,
        cost_usd=total_cost,
    )


def accumulate_usage(usage: TokenUsage):
    _usage["total_requests"] += 1
    _usage["total_input_tokens"] += usage.input_tokens
    _usage["total_output_tokens"] += usage.output_tokens
    _usage["total_tokens"] += usage.total_tokens
    _usage["total_cost_usd"] += usage.cost_usd
    print(
        f"[usage] req #{_usage['total_requests']} "
        f"in={usage.input_tokens} out={usage.output_tokens} "
        f"cost=${usage.cost_usd:.6f} | "
        f"session total=${_usage['total_cost_usd']:.4f}"
    )


def find_report_path(messages: list) -> str | None:
    for message in messages:
        if type(message).__name__ != "ToolMessage":
            continue
        content = getattr(message, "content", "")
        if (
            isinstance(content, str)
            and content.startswith("reports/")
            and content.endswith(".md")
        ):
            return content
    return None


def find_table_path(messages: list) -> str | None:
    """Find the file path from a query_to_inline_table tool call.

    The tool's output looks like:
        reports/query_2025-06-30_143022.md
        Rows: 150
        Title: All Donations from June

    We extract just the first line (the path).
    """
    for message in messages:
        if type(message).__name__ != "ToolMessage":
            continue
        content = getattr(message, "content", "")
        if (
            isinstance(content, str)
            and content.startswith("reports/")
            and "Rows:" in content
        ):
            return content.splitlines()[0].strip()
    return None


def extract_steps(messages: list) -> list[AgentStep]:
    steps = []
    for message in messages:
        class_name = type(message).__name__
        if class_name == "AIMessage":
            tool_calls = getattr(message, "tool_calls", []) or []
            for tc in tool_calls:
                tool_name = tc.get("name", "")
                tool_args = tc.get("args", {})
                if tool_name == "execute_sql_query":
                    query = tool_args.get("query", "").strip()
                    if len(query) > 120:
                        short_query = query[:120] + "…"
                    else:
                        short_query = query
                    steps.append(AgentStep(label="Running SQL", detail=short_query))
                elif tool_name == "query_to_inline_table":
                    query = tool_args.get("query", "").strip()
                    if len(query) > 120:
                        short_query = query[:120] + "…"
                    else:
                        short_query = query
                    steps.append(
                        AgentStep(label="Querying full dataset", detail=short_query)
                    )
                elif tool_name == "generate_static_report":
                    title = tool_args.get("title", "")
                    report_type = tool_args.get("report_type", "")
                    if title:
                        detail = report_type + ": " + title
                    else:
                        detail = report_type
                    steps.append(AgentStep(label="Generating report", detail=detail))
                elif tool_name == "generate_dynamic_report":
                    title = tool_args.get("title", "")
                    steps.append(AgentStep(label="Generating report", detail=title))
                else:
                    steps.append(
                        AgentStep(
                            label=f"Calling {tool_name}", detail=str(tool_args)[:120]
                        )
                    )
        elif class_name == "ToolMessage":
            content = getattr(message, "content", "") or ""
            if isinstance(content, str) and content.startswith("Error:"):
                steps.append(AgentStep(label="Tool call failed", detail=content[:120]))
            elif (
                isinstance(content, str)
                and content.startswith("reports/")
                and "Rows:" in content
            ):
                first_line = content.splitlines()[0].strip()
                steps.append(AgentStep(label="Table saved", detail=first_line))
            elif isinstance(content, str) and content.startswith("reports/"):
                steps.append(AgentStep(label="Report saved", detail=content))
            else:
                lines = []
                for l in content.strip().splitlines():
                    if l.strip():
                        lines.append(l)
                row_count = max(0, len(lines) - 1)
                if lines:
                    preview = lines[0][:80]
                else:
                    preview = ""
                row_label = "row"
                if row_count != 1:
                    row_label = "rows"
                label = str(row_count) + " " + row_label + " returned"
                steps.append(AgentStep(label=label, detail=preview))
    return steps


from app.database import get_session


@router.post("/chat/", response_model=ChatResponse)
def chat_endpoint(payload: ChatRequest, db: Session = Depends(get_session)):
    agent = get_current_agent()
    callback = HallucinationCallback()
    config = {
        "configurable": {"thread_id": payload.thread_id},
        "metadata": {
            "user_id": payload.user_id,
            "thread_id": payload.thread_id,
        },
        "callbacks": [callback],
    }
    result = agent.invoke({"messages": [("user", payload.message)]}, config=config)
    messages = result["messages"]
    last_message = messages[-1]

    response_text = extract_content(last_message)
    usage = extract_usage(messages)
    accumulate_usage(usage)
    if usage:
        usage_dump = usage.model_dump()
    else:
        usage_dump = None

    if payload.user_id is not None:
        thread_name = payload.message[:80]
        logging_turns(
            db,
            user_id=payload.user_id,
            thread_id=payload.thread_id,
            thread_name=thread_name,
            role="user",
            content=payload.message,
        )
        logging_turns(
            db,
            user_id=payload.user_id,
            thread_id=payload.thread_id,
            thread_name=thread_name,
            role="assistant",
            content=response_text,
        )
    _write_trace_log(
        payload.thread_id,
        payload.message,
        messages,
        usage_dump,
    )
    report_path = find_report_path(messages)
    table_path = find_table_path(messages)
    steps = extract_steps(messages)

    return ChatResponse(
        response=response_text,
        thread_id=payload.thread_id,
        usage=usage,
        report_path=report_path,
        table_path=table_path,
        steps=steps,
        eval_warnings=callback.get_warnings(),
    )


@router.post("/chat/stream/")
async def chat_stream(payload: ChatRequest, db: Session = Depends(get_session)):
    agent = get_current_agent()
    callback = HallucinationCallback()
    config = {
        "configurable": {"thread_id": payload.thread_id},
        "metadata": {
            "user_id": payload.user_id,
            "thread_id": payload.thread_id,
        },
        "callbacks": [callback],
    }

    async def event_generator():
        report_path = None
        table_path = None
        total_input = 0
        total_output = 0
        trace_lines: list[str] = []  # collected for trace log
        response_text: list[str] = []

        try:
            async for event in agent.astream_events(
                {"messages": [("user", payload.message)]},
                config=config,
                version="v2",
            ):
                kind = event["event"]

                if kind == "on_tool_start":
                    tool_name = event.get("name", "")
                    if tool_name == "execute_sql_query":
                        tool_input = event.get("data", {}).get("input", {}) or {}
                        query = tool_input.get("query", "")
                        trace_lines.append(
                            f"### execute_sql_query\n\n```sql\n{query}\n```\n\n"
                        )
                        yield _sse(
                            {
                                "type": "step",
                                "label": "Querying database",
                                "detail": query[:120],
                            }
                        )
                    elif tool_name == "query_to_inline_table":
                        tool_input = event.get("data", {}).get("input", {}) or {}
                        query = tool_input.get("query", "")
                        trace_lines.append(
                            f"### query_to_inline_table\n\n```sql\n{query}\n```\n\n"
                        )
                        yield _sse(
                            {
                                "type": "step",
                                "label": "Querying full dataset",
                                "detail": query[:120],
                            }
                        )
                    elif tool_name == "generate_static_report":
                        tool_input = event.get("data", {}).get("input", {}) or {}
                        title = tool_input.get("title", "")
                        trace_lines.append(f"### generate_static_report\n\n{title}\n\n")
                        yield _sse(
                            {
                                "type": "step",
                                "label": "Generating report",
                                "detail": title,
                            }
                        )
                    elif tool_name == "generate_dynamic_report":
                        tool_input = event.get("data", {}).get("input", {}) or {}
                        title = tool_input.get("title", "")
                        trace_lines.append(
                            f"### generate_dynamic_report\n\n{title}\n\n"
                        )
                        yield _sse(
                            {
                                "type": "step",
                                "label": "Generating report",
                                "detail": title,
                            }
                        )
                    else:
                        trace_lines.append(f"### {tool_name}\n\n")
                        yield _sse(
                            {
                                "type": "step",
                                "label": f"Running {tool_name}",
                                "detail": "",
                            }
                        )

                elif kind == "on_tool_end":
                    output = _tool_output_str(event.get("data", {}).get("output", ""))

                    if output.startswith("Error:"):
                        if output.startswith("Error: "):
                            err_detail = output[7:]
                        else:
                            err_detail = ""
                        trace_lines.append(f"**Error:** {err_detail[:200]}\n\n")
                        yield _sse(
                            {
                                "type": "step",
                                "label": "Query failed",
                                "detail": err_detail[:120],
                            }
                        )
                    elif output.startswith("reports/") and "Rows:" in output:
                        table_path = output.splitlines()[0].strip()
                        split_lines = output.splitlines()
                        if len(split_lines) > 1:
                            rows_info = split_lines[1]
                        else:
                            rows_info = ""
                        trace_lines.append(
                            "Saved: `" + table_path + "`\n\nRows: " + rows_info + "\n\n"
                        )
                        yield _sse(
                            {"type": "step", "label": "Table saved", "detail": ""}
                        )
                    elif output.startswith("reports/"):
                        report_path = output
                        trace_lines.append(f"Saved: `{output}`\n\n")
                        yield _sse(
                            {"type": "step", "label": "Report saved", "detail": ""}
                        )
                    elif output == "No results found.":
                        trace_lines.append(f"0 rows returned\n\n")
                        yield _sse(
                            {"type": "step", "label": "0 rows returned", "detail": ""}
                        )
                    else:
                        lines = []
                        for l in output.strip().splitlines():
                            if l.strip():
                                lines.append(l)
                        row_count = max(0, len(lines) - 1)
                        row_label = "row"
                        if row_count != 1:
                            row_label = "rows"
                        label = str(row_count) + " " + row_label + " returned"
                        trace_lines.append(
                            str(row_count) + " " + row_label + " returned\n\n"
                        )
                        yield _sse({"type": "step", "label": label, "detail": ""})

                elif kind == "on_chat_model_stream":
                    chunk = event.get("data", {}).get("chunk")
                    if chunk is None:
                        continue
                    # Skip chunks that only carry tool-call deltas — we want text.
                    if getattr(chunk, "tool_call_chunks", None):
                        continue
                    for t in _iter_chunk_texts(getattr(chunk, "content", "")):
                        response_text.append(t)
                        yield _sse({"type": "chunk", "text": t})

                elif kind == "on_chat_model_end":
                    meta = event.get("data", {}).get("output")
                    if meta:
                        usage_meta = getattr(meta, "usage_metadata", None)
                    else:
                        usage_meta = None
                    if usage_meta:
                        total_input += usage_meta.get("input_tokens", 0)
                        total_output += usage_meta.get("output_tokens", 0)

        except Exception as exc:
            trace_text = "".join(response_text).strip()
            try:
                _write_trace_from_parts(
                    thread_id=payload.thread_id,
                    user_message=payload.message,
                    trace_lines=trace_lines,
                    response_text=trace_text,
                    error=traceback.format_exc(),
                )
            except Exception:
                pass
            yield _sse({"type": "error", "message": str(exc)})
            return

        input_cost = (total_input / 1000) * INPUT_TOKEN_PRICE_PER_1K
        output_cost = (total_output / 1000) * OUTPUT_TOKEN_PRICE_PER_1K
        usage = {
            "input_tokens": total_input,
            "output_tokens": total_output,
            "total_tokens": total_input + total_output,
            "cost_usd": round(input_cost + output_cost, 6),
        }
        accumulate_usage(TokenUsage(**usage))

        trace_text = "".join(response_text).strip()
        _write_trace_from_parts(
            thread_id=payload.thread_id,
            user_message=payload.message,
            trace_lines=trace_lines,
            response_text=trace_text,
            usage=usage,
        )

        if payload.user_id is not None:
            thread_name = payload.message[:80]
            logging_turns(
                db,
                user_id=payload.user_id,
                thread_id=payload.thread_id,
                thread_name=thread_name,
                role="user",
                content=payload.message,
            )
            logging_turns(
                db,
                user_id=payload.user_id,
                thread_id=payload.thread_id,
                thread_name=thread_name,
                role="assistant",
                content=trace_text,
            )

        for warning in callback.get_warnings():
            yield _sse({"type": "eval_warning", "message": warning})

        yield _sse(
            {
                "type": "done",
                "thread_id": payload.thread_id,
                "report_path": report_path,
                "table_path": table_path,
                "usage": usage,
            }
        )

    return StreamingResponse(
        event_generator(),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "X-Accel-Buffering": "no",
            "Connection": "keep-alive",
        },
    )


@router.get("/usage/", response_model=UsageStats)
def usage_stats():
    pricing_is_configured = (
        INPUT_TOKEN_PRICE_PER_1K > 0 or OUTPUT_TOKEN_PRICE_PER_1K > 0
    )
    return UsageStats(
        **_usage,
        pricing_configured=pricing_is_configured,
    )
