import os
import sqlite3
from datetime import datetime
from urllib.parse import urlparse

from langchain_core.tools import tool

from app.config import DATABASE_URL


def _resolve_db_path() -> str:
    """
    Convert the DATABASE_URL from config into an absolute file path.

    SQLite URLs look like 'sqlite:///vetlog.db' or 'sqlite:////abs/path.db'.
    urlparse gives us the path portion. If it is relative, we resolve it
    against the project root (one directory above this file's package).

    Returns:
        The absolute path to the SQLite database file.
    """
    project_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

    parsed = urlparse(DATABASE_URL)
    db_path = parsed.path

    # urlparse includes a leading slash for absolute paths — strip it for
    # relative paths so os.path.join works correctly.
    if db_path.startswith("/"):
        db_path = db_path.lstrip("/")

    if os.path.isabs(db_path):
        return db_path

    resolved = os.path.join(project_root, db_path)

    # Fall back to a sensible default if the URL was empty or malformed.
    if not resolved:
        return os.path.join(project_root, "vetlog.db")

    return resolved


DB_PATH = _resolve_db_path()

REPORTS_DIR = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "app", "reports"
)
os.makedirs(REPORTS_DIR, exist_ok=True)
"""Right now the report templates are hardcoded but what if i wanted a freeflow report then what?"""
_REPORT_TEMPLATES = {
    "daily_summary": "## Daily Clinic Summary — {date}\n\n{summary}\n\n### {title}\n\n{table}\n\n---\n*Generated by Vetlog AI Assistant*",
    "donation_ledger": "## Donation Ledger — {date}\n\n{summary}\n\n### {title}\n\n{table}\n\n---\n*Generated by Vetlog AI Assistant*",
    "treatment_log": "## Treatment Log — {date}\n\n{summary}\n\n### {title}\n\n{table}\n\n---\n*Generated by Vetlog AI Assistant*",
    "attendance_sheet": "## Attendance Sheet — {date}\n\n{summary}\n\n### {title}\n\n{table}\n\n---\n*Generated by Vetlog AI Assistant*",
}


def _tsv_to_markdown_table(data: str) -> str:
    """Convert tab-separated data into a GitHub-flavoured markdown table."""
    lines = data.strip().split("\n")
    if not lines:
        return "_No data._"

    header = lines[0].split("\t")
    rows = []
    for line in lines[1:]:
        rows.append(line.split("\t"))

    md = "| " + " | ".join(header) + " |\n"

    sep = "| "
    for i in range(len(header)):
        if i > 0:
            sep += " | "
        sep += "---"
    sep += " |\n"
    md += sep

    for row in rows:
        md += "| " + " | ".join(row) + " |\n"

    return md


def _rows_with_display_timestamps(column_names, rows):
    """
    Convert ISO-8601 timestamps (24-hour) to 12-hour AM/PM format
    for display. Keeps 24-hour storage intact for SQL range queries.
    """
    if not rows:
        return rows

    ts_idx = None
    idx = 0
    for col in column_names:
        if col.lower() == "timestamp":
            ts_idx = idx
            break
        idx += 1

    if ts_idx is None:
        return rows

    formatted = []
    for row in rows:
        new_row = list(row)
        cell_val = new_row[ts_idx]
        if cell_val is not None:
            val = str(cell_val)
        else:
            val = ""
        if val.startswith("202"):
            try:
                dt = datetime.strptime(val, "%Y-%m-%d %H:%M:%S")
                new_row[ts_idx] = dt.strftime("%b %d, %Y %I:%M %p")
            except ValueError:
                pass
        formatted.append(tuple(new_row))
    return formatted


@tool
def generate_static_report(
    report_type: str,
    title: str,
    query: str,
    summary: str = "",
    date: str = "",
) -> str:
    """
    Generate a formatted Markdown report using a predefined template and save it.

    1. Use this when the user's report request fits one of the 4 standard
    2. categories: daily_summary, donation_ledger, treatment_log, or attendance_sheet.
    3. For reports about a specific date: ALWAYS pass the date parameter to generate_static_report
      (e.g. date='2026-03-27') so the title and filename use the report's subject date, not today.
    4. Provide the exact SQL query in the 'query' parameter (e.g. SELECT sender, text, timestamp FROM raw_messages...).
       The tool will execute the query and format the results directly. Omit id and captured_at.

    Call this tool when the user asks for a structured report. The report is written to 
    the reports/ directory and its filename is returned — the UI will display the markdown.
    
    IMPORTANT: DO NOT use this tool if you are also calling query_to_inline_table 
    or generate_dynamic_report. Choose EXACTLY ONE reporting tool to display data.

    IMPORTANT: When you call generate_static_report, do NOT repeat the data in your
      text reply. Just confirm in one sentence that the report is ready.

    Args:
        report_type: One of 'daily_summary', 'donation_ledger', 'treatment_log', 'attendance_sheet'.
        title:       A short human-readable title for the report (e.g. 'June 24 Clinic Activity').
        query:       The exact SQLite SELECT query to fetch the report data.
        summary:     A 2-3 sentence summary of what the report contains (patient count, key events, totals).
        date:        The SUBJECT date of the report (e.g. '2026-03-27'), NOT today's date.

    Returns:
        The filename of the saved report.
    """
    if report_type not in _REPORT_TEMPLATES:
        template_keys = ""
        for key in _REPORT_TEMPLATES:
            if template_keys:
                template_keys += ", "
            template_keys += key
        return (
            "Error: Unknown report_type '"
            + report_type
            + "'. Choose from: "
            + template_keys
        )

    connection = sqlite3.connect(DB_PATH)
    try:
        cursor = connection.cursor()
        cursor.execute(query)
        rows = cursor.fetchall()
        column_names = [desc[0] for desc in cursor.description]
        rows = _rows_with_display_timestamps(column_names, rows)
        
        data_lines = []
        for row in rows:
            data_lines.append("\t".join(str(cell) for cell in row))
        tsv = "\t".join(column_names) + "\n" + "\n".join(data_lines) if data_lines else "No results found."
        table_md = _tsv_to_markdown_table(tsv) if data_lines else "_No data found for this query._"
    except Exception as e:
        return f"Error executing query for report: {e}"
    finally:
        connection.close()

    date_str = date or datetime.now().strftime("%Y-%m-%d")

    safe_title = title.lower().replace(" ", "_")[:30]
    filename = f"{report_type}_{date_str}_{safe_title}.md"
    filepath = os.path.join(REPORTS_DIR, filename)

    template = _REPORT_TEMPLATES[report_type]
    if summary:
        final_summary = summary
    else:
        final_summary = "Report: " + title
    content = template.format(
        date=date_str,
        title=title,
        table=table_md,
        summary=final_summary,
    )

    with open(filepath, "w") as f:
        f.write(content)

    return f"reports/{filename}"


@tool
def generate_dynamic_report(title: str, content: str) -> str:
    """
    Save a free-form Markdown report to a file.

    1. Use this when the user's request does NOT fit a standard template.
    2. Write the full Markdown content yourself — any structure, any format.
    3. For standard categories (daily_summary, donation_ledger, treatment_log,
    attendance_sheet), use generate_static_report instead.
    4. When writing reports with 20+ rows: group entries by week or condition instead of
      listing every single row. Use the full data to produce an informative summary — never
      abbreviate rows with "..." or "(continued)" placeholders.

    IMPORTANT: When you call generate_dynamic_report, do NOT repeat the data in your
      text reply. The UI already shows the report/table as a preview card. Just confirm
      in one sentence that the report is ready (e.g. "Your treatment history report is ready.").

    Args:
        title:   A short human-readable title for the report
                 (e.g. 'Rocky Treatment History').
        content: The full Markdown content of the report.

    Returns:
        The filename of the saved report (e.g. 'reports/rocky_treatment_2025-06-25.md').
    """
    date_str = datetime.now().strftime("%Y-%m-%d")
    safe_title = title.lower().replace(" ", "_").replace("/", "_")[:30]
    filename = f"{safe_title}_{date_str}.md"
    filepath = os.path.join(REPORTS_DIR, filename)

    with open(filepath, "w", encoding="utf-8") as f:
        f.write(f"## {title}\n\n*Generated {date_str}*\n\n{content}\n")

    return f"reports/{filename}"


"""We might need a detailed report tool we already have one that gives concise
but what if the dude asks a detailed report then we might have to give it to them"""


@tool
def execute_sql_query(query: str) -> str:
    """
    Execute a read-only SQL query against the Vetlog SQLite database.

    The database has one table — raw_messages — which stores WhatsApp
    messages scraped from the clinic's group chats. Use this tool after
    writing the correct SQL for the user's question. If the query fails,
    the error message is returned so you can fix and retry.

    SQL patterns for this DB:
    - Use LIKE with wildcards for text searches (e.g. WHERE text LIKE '%Rocky%')
    - Use GROUP BY and COUNT for summaries
    - Never invent data — only return what the query actually finds
    - Default chat names in the DB follow a prefix pattern; use LIKE for matching
    - This tool returns a MAXIMUM OF 100 ROWS. If you need fewer rows, use LIMIT in your SQL.
    - If you hit the 100-row limit and need all the data, DO NOT paginate with OFFSET. Use query_to_inline_table.

    Args:
        query: A valid SQLite SELECT statement.

    Returns:
        A tab-separated string of results (header row + data rows),
        'No results found.' if the query matched nothing,
        or an error message if the query was invalid.
    """
    connection = sqlite3.connect(DB_PATH)

    try:
        cursor = connection.cursor()
        cursor.execute(query)
        rows = cursor.fetchall()

        if not rows:
            return "No results found."

        column_names = []
        for description in cursor.description:
            column_names.append(description[0])
        header = "\t".join(column_names)
        MAX_ROWS = 100
        data_rows = []
        for row in rows[:MAX_ROWS]:
            row_str = ""
            for cell in row:
                if row_str:
                    row_str += "\t"
                row_str += str(cell)
            data_rows.append(row_str)

        result = header + "\n" + "\n".join(data_rows)

        if len(rows) > MAX_ROWS:
            result += f"\n... and {len(rows) - MAX_ROWS} more rows"

        return result

    except Exception as error:
        return f"Error: {error}"

    finally:
        connection.close()


@tool
def query_to_inline_table(query: str, title: str = "Query Results") -> str:
    """
    Execute a SELECT query and save the FULL result set as a Markdown table
    to a file. Use this when the user wants to see ALL rows or a large dataset
    (e.g. "show all donations", "list every message from June").

    Unlike execute_sql_query (which caps at 100 rows), this tool runs the query
    unbounded and writes every row to a file. The file path is returned — the
    UI renders the full table inline in the chat, bypassing the LLM context
    limit entirely.
    
    IMPORTANT: DO NOT use this tool if you are also calling generate_static_report 
    or generate_dynamic_report. Choose EXACTLY ONE tool to present data.

    Only SELECT statements are allowed. A safety cap of 5000 rows prevents
    pathological queries.

    Args:
        query: A valid SQLite SELECT statement.
        title: A short human-readable title for the result set
               (e.g. 'All Donations from June').

    Returns:
        The file path, row count, and title — or an error message.
        Example: 'reports/query_2025-06-30_143022.md\\nRows: 150\\nTitle: All Donations from June'
    """
    # Only SELECT queries allowed — this tool runs unbounded.
    if not query.lstrip().upper().startswith("SELECT"):
        return "Error: query_to_inline_table only accepts SELECT statements."

    connection = sqlite3.connect(DB_PATH)

    try:
        cursor = connection.cursor()
        cursor.execute(query)
        rows = cursor.fetchall()

        if not rows:
            return "No results found."

        column_names = []
        for description in cursor.description:
            column_names.append(description[0])
        # Convert timestamps from 24-hour ISO to 12-hour display
        rows = _rows_with_display_timestamps(column_names, rows)

        # Safety cap — 5000 rows is enough for any realistic clinic dataset
        # and prevents a runaway query from producing a massive file.
        MAX_ROWS = 5000
        truncated = len(rows) > MAX_ROWS
        rows_to_write = rows[:MAX_ROWS]

        # Build data lines manually
        data_lines = []
        for row in rows_to_write:
            row_str = ""
            for cell in row:
                if row_str:
                    row_str += "\t"
                row_str += str(cell)
            data_lines.append(row_str)
        header = "\t".join(column_names)
        tsv = header + "\n" + "\n".join(data_lines)
        table_md = _tsv_to_markdown_table(tsv)

        # Build the file content with a header and row count.
        date_str = datetime.now().strftime("%Y-%m-%d %H:%M")
        row_note = f"{len(rows)} rows"
        if truncated:
            row_note += f" (showing first {MAX_ROWS})"
        content = (
            f"## {title}\n\n"
            f"*{row_note} \u00b7 {date_str}*\n\n"
            f"{table_md}\n\n"
            f"---\n*Generated by Vetlog AI Assistant*"
        )

        # Save to the reports directory.
        safe_title = title.lower().replace(" ", "_")[:30]
        timestamp = datetime.now().strftime("%Y-%m-%d_%H%M%S")
        filename = f"query_{timestamp}_{safe_title}.md"
        filepath = os.path.join(REPORTS_DIR, filename)

        with open(filepath, "w") as f:
            f.write(content)

        return f"reports/{filename}\nRows: {len(rows)}\nTitle: {title}"

    except Exception as error:
        return f"Error: {error}"

    finally:
        connection.close()
